#!/bin/bash

# Import scripts
. ./local_build 
. ./local_install_conda 
. ./local_install_mamba 
. ./local_start 

set -e

# Arguments: 
$0 = overlay
$1 = command
$2 = project_name

# Functions: 

help(){
cat << _EOF_
    Overlay Tool Documentation

    Usage: overlay [command] [name] [project_name]

    Commands:
    --help          Show this help message
    --create        Create an overlay virtual environment
    --activate      Activate an overlay environment
    --deactivate    Deactivate and zip the overlay environment

    Arguments:
    command         The command to be executed (required)
    name            The name of the overlay environment (default: "myenv")
    project_name    The name of the project associated with the environment (default: "myproject")

    Examples:
    overlay --create myenv myproject    # Create a virtual environment named "myenv" for project "myproject"
    overlay --activate myenv           # Activate the "myenv" environment
    overlay --deactivate               # Deactivate and zip the current environment

    Please refer to the overlay tool documentation for more information.
_EOF_
}


# Create the commands
if [ "$1" == "--install"]; then
./local_build
./local_install_conda
fi

if [ "$1" == "--activate"]; then
./local_start
fi

if ["$1" == "--deactivate"]; then
 # script to deactivate the env
fi

if [ "$1" == "--help"]; then
help
exit 1
fi

if [ -n "$1"]; then
echo "Overlay error: Invalid argument: Try overlay --help for more information" >&2
exit 1
fi


